// BUILD-77 — WHAT A REAL FILE DID TO US, pinned forever.
//
// A 2,502-row messy donor export imported into a fresh production org
// produced four findings; this suite is the golden-file regression. The
// fixture is the REAL file (tests/fixtures/build77/steward-messy-2500.csv);
// the answer key (answer-key.json) was generated by an INDEPENDENT
// implementation of the disposition policy (gen-answer-key.mjs — raw CSV +
// the spec's rules, never the import code under test), because the original
// failure was precisely an invariant grading its own homework: the summary
// read "In your file 2,428 / Balanced" while 74 rows and ~$154,806 sat
// dropped on the floor (54 of them "USD 750.00"-style amounts).
//
//   §1  the REAL auto-mapping claims every column with a schema home; the
//       four homeless columns are named (the acknowledge list)
//   §2  the accounted builder: every one of the 2,502 physical rows has
//       EXACTLY ONE disposition, and every bucket matches the key by count
//       AND by dollars (totals are what hid this — never totals alone)
//   §3  through the real route: DB row/dollar truth, Larry Ackerly's dates
//       (no gift ever dated today), refunds negative, flags set, sustainers
//       marked — and the file-level equation balances against 2,502
//   §4  the exclusion sections of the key are ABSENT from every actionable
//       surface, by name (drift, needs-attention, at-risk candidates)
//
// FAILS-FIRST RECORD (2026-09-03, pre-fix reproduction, audit/BUILD-77):
// payload gifts 2,428 of 2,502 · summary "Balanced" · Larry Ackerly's
// unparseable "03-16-2020" became a gift dated TODAY in the browser · 14
// gifts landed dated >= today · drift list carried Harold Isley (DNC) and
// two pledge payers · recurring surface read zero with 34 sustainers on file.
//
// Local scratch server + Postgres (tests/README.md recipe).

const fs = require("fs");
const path = require("path");
const bcrypt = require("bcryptjs");
const { BASE, ok, summary, login, api, q, closeDb } = require("./helpers");

const ORG = "org_b77golden";
const FIXTURE = path.join(__dirname, "fixtures", "build77", "steward-messy-2500.csv");
const KEY = JSON.parse(fs.readFileSync(path.join(__dirname, "fixtures", "build77", "answer-key.json"), "utf8"));

// Minimal quoted-CSV parser (the client uses Papa; this suite must not
// depend on client/node_modules — the grammar for this file is identical).
function parseCsv(t) {
  const rows = []; let row = [], cell = "", quoted = false;
  for (let i = 0; i < t.length; i++) {
    const c = t[i];
    if (quoted) { if (c === '"') { if (t[i + 1] === '"') { cell += '"'; i++; } else quoted = false; } else cell += c; }
    else if (c === '"') quoted = true;
    else if (c === ",") { row.push(cell); cell = ""; }
    else if (c === "\n") { row.push(cell.replace(/\r$/, "")); rows.push(row); row = []; cell = ""; }
    else cell += c;
  }
  if (cell !== "" || row.length) { row.push(cell); rows.push(row); }
  return rows;
}

async function reset() {
  for (const t of ["workflow_runs", "workflows", "digest_sends", "moves", "opportunities", "tasks",
    "payment_recovery_events", "reconnect_sends", "recurring_subscriptions", "receipts", "pledges", "fin_audit_log",
    "fin_transactions", "gifts", "interactions", "milestone_drafts", "note_reminders",
    "fundraising_goals", "metric_snapshots", "donors", "campaigns", "fin_funds", "accounts", "budgets", "users"])
    await q(`DELETE FROM ${t} WHERE org_id=$1`, [ORG]).catch(() => {});
  await q(`DELETE FROM orgs WHERE id=$1`, [ORG]).catch(() => {});
  await q(`INSERT INTO orgs (id,name,org_slug,onboarding_complete,subscription_status,plan)
           VALUES ($1,'B77 Golden','b77-golden',1,'active','team')`, [ORG]);
  await q(`INSERT INTO users (id,org_id,email,password_hash,name,role)
           VALUES ('u_b77golden',$1,'b77golden@test.local',$2,'Golden Admin','admin')`,
    [ORG, bcrypt.hashSync("loadtest1234", 10)]);
  await q(`INSERT INTO accounts (id,org_id,code,name,type) VALUES ('acct_b77g',$1,'4010','Contributions','revenue')`, [ORG]);
  await q(`INSERT INTO fin_funds (id,org_id,name,restricted) VALUES ('fund_b77g',$1,'General',false)`, [ORG]);
}

(async () => {
  await reset();
  const tok = await login("b77golden@test.local");
  const lib = await import("../shared/importShape.js");
  const TODAY = new Date().toISOString().slice(0, 10);

  // The key was generated on a fixed day; future-vs-today moves with the
  // calendar, so re-derive: a key row errored as future_date whose date has
  // since arrived is expected to be a gift on THIS run.
  const expected = KEY.dispositions.map(d =>
    d.reason === "future_date" && d.date && d.date <= TODAY
      ? { ...d, disposition: "gift", reason: null }
      : d);
  const exp = {
    gift: expected.filter(d => d.disposition === "gift"),
    skipped: expected.filter(d => d.disposition === "skipped"),
    errored: expected.filter(d => d.disposition === "errored"),
  };
  const expDollars = b => Math.round(exp[b].reduce((s, d) => s + d.dollars, 0) * 100) / 100;

  // ── §1 · the REAL auto-mapping ───────────────────────────────────────────
  console.log("\n— §1 · every column with a home is claimed; the homeless are named —");
  const raw = parseCsv(fs.readFileSync(FIXTURE, "utf8"));
  const headers = raw[0].map(h => h.trim());
  const bodyRows = raw.slice(1)
    .filter(r => r.some(c => String(c).trim() !== ""))
    .map(r => Object.fromEntries(headers.map((h, i) => [h, r[i] ?? ""])));
  ok("physical non-blank rows = 2,502 (counted once, at parse entry)", bodyRows.length === KEY.file.physicalRows, bodyRows.length);

  const txMap = lib.autoDetectTxMapping(headers, bodyRows.slice(0, 10));
  for (const [role, col] of [["donorName", "Donor Name"], ["donorEmail", "Email"], ["amount", "Amount"], ["date", "Gift Date"],
    ["phone", "Phone"], ["address", "Address"], ["city", "City"], ["state", "State"], ["zip", "ZIP"],
    ["type", "Payment Method"], ["campaign", "Campaign"], ["notes", "Notes"]]) {
    ok(`auto-map claims ${col}`, txMap[role] === col, { role, got: txMap[role] });
  }
  const mapped = new Set(Object.values(txMap).filter(Boolean));
  const homeless = headers.filter(h => h && !mapped.has(h));
  ok("exactly the four homeless columns remain for acknowledgement (Fund, Donor Type, Source, Legacy ID)",
    homeless.sort().join("|") === ["Donor Type", "Fund", "Legacy ID", "Source"].join("|"), homeless);

  // ── §2 · the accounted builder: every row, exactly one disposition ───────
  console.log("\n— §2 · dispositions by count AND by dollars —");
  const built = lib.buildTransactionRows({ rows: bodyRows }, txMap, { today: TODAY });
  ok("every physical row received exactly one disposition (the test fails if any row lacks one)",
    built.dispositions.length === KEY.file.physicalRows
    && new Set(built.dispositions.map(d => d.line)).size === KEY.file.physicalRows,
    built.dispositions.length);
  ok(`gift rows: ${exp.gift.length}`, built.file.imported === exp.gift.length, { got: built.file.imported });
  ok(`skipped rows: ${exp.skipped.length}`, built.file.skipped === exp.skipped.length, { got: built.file.skipped });
  ok(`errored rows: ${exp.errored.length}`, built.file.errored === exp.errored.length, { got: built.file.errored });
  const builtGiftDollars = Math.round(built.dispositions.filter(d => d.disposition === "gift").reduce((s, d) => s + d.dollars, 0) * 100) / 100;
  ok(`gift DOLLARS match the key ($${expDollars("gift")}) — dollars, not just rows`,
    Math.abs(builtGiftDollars - expDollars("gift")) < 0.01, builtGiftDollars);
  // per-reason parity with the key
  for (const reason of Object.keys(KEY.reasons)) {
    const expN = expected.filter(d => d.reason === reason).length;
    const gotN = built.dispositions.filter(d => d.reason === reason).length;
    ok(`reason ${reason}: ${expN} rows`, gotN === expN, { got: gotN });
  }
  // the USD family specifically — the $154,849.63 that vanished
  const usdRows = bodyRows.filter(r => /^USD /i.test(String(r["Amount"]).trim()));
  ok("all 54 'USD 750.00'-style rows now parse as gifts ($154,849.63 recovered)",
    usdRows.length === 54 && usdRows.every(r => lib.normalizeMoney(r["Amount"]).value > 0), usdRows.length);
  // flags cover the key's exclusion names
  const flaggedNames = new Set(built.flaggedRows.map(f => f.name));
  for (const name of [...KEY.exclusions.deceased, ...KEY.exclusions.doNotSolicit, ...KEY.exclusions.doNotContact].slice(0, 50)) {
    if (![...flaggedNames].some(n => n.toLowerCase() === name.toLowerCase()))
      ok(`flagged list covers ${name}`, false, [...flaggedNames].slice(0, 8));
  }
  ok("every deceased/do-not-solicit/do-not-contact donor in the key appears on the flagged list",
    [...KEY.exclusions.deceased, ...KEY.exclusions.doNotSolicit, ...KEY.exclusions.doNotContact]
      .every(n => [...flaggedNames].some(f => f.toLowerCase() === n.toLowerCase())), null);
  // sustainers (pledge cadence excluded from the evidence)
  const susBuilt = built.donors.filter(d => d.importedSustainer).map(d => d.name).sort();
  ok(`imported sustainers detected: ${KEY.sustainers.count} (interval evidence outranks the note; pledge cadence never counts)`,
    susBuilt.length === KEY.sustainers.count, { got: susBuilt.length });
  ok("…and they are the key's 34 by name",
    JSON.stringify(susBuilt.map(s => s.toLowerCase())) === JSON.stringify(KEY.sustainers.names.map(s => s.toLowerCase()).sort()),
    susBuilt.filter(n => !KEY.sustainers.names.some(k => k.toLowerCase() === n.toLowerCase())));

  // ── §3 · through the real route ──────────────────────────────────────────
  console.log("\n— §3 · the real route: DB truth, the file-level equation —");
  const CHUNK = 500;
  const byDonor = new Map();
  for (const g of built.gifts) { if (!byDonor.has(g.donorIndex)) byDonor.set(g.donorIndex, []); byDonor.get(g.donorIndex).push(g); }
  let created = 0, sumRecon = { rows: { inFile: 0, created: 0, skipped: 0, errored: 0 }, dollars: { created: 0, skipped: 0, errored: 0 } };
  for (let start = 0; start < built.donors.length; start += CHUNK) {
    const slice = built.donors.slice(start, start + CHUNK);
    const chunkGifts = [];
    slice.forEach((_, li) => { const gg = byDonor.get(start + li); if (gg) gg.forEach(g => { const { donorIndex, ...rest } = g; chunkGifts.push({ ...rest, donorIndex: li }); }); });
    const res = await api("POST", "/donors/import-combined", tok, { donors: slice, gifts: chunkGifts });
    if (res.status !== 200) { ok("chunk imports (status 200)", false, { status: res.status, body: JSON.stringify(res.body).slice(0, 200) }); break; }
    created += res.body.created || 0;
    const rr = res.body.reconciliation;
    sumRecon.rows.created += rr.rows.created; sumRecon.rows.skipped += rr.rows.skipped; sumRecon.rows.errored += rr.rows.errored;
    sumRecon.dollars.created += rr.dollars.created; sumRecon.dollars.skipped += rr.dollars.skipped; sumRecon.dollars.errored += rr.dollars.errored;
  }
  // the FILE-level equation, exactly as the client now computes it
  const clientRefused = built.dispositions.filter(d => d.disposition !== "gift");
  const fileAccounted = sumRecon.rows.created + sumRecon.rows.skipped + sumRecon.rows.errored + clientRefused.length;
  ok(`the file-level equation closes: 2,502 = server(created+skipped+errored) + client-refused (${fileAccounted})`,
    fileAccounted === KEY.file.physicalRows, { server: sumRecon.rows, clientRefused: clientRefused.length });

  const [dbGifts] = await q(`SELECT COUNT(*)::int n, COALESCE(SUM(amount),0)::float d FROM gifts WHERE org_id=$1`, [ORG]);
  ok(`DB gift rows == the key (${exp.gift.length}) — nothing silently gone, nothing invented`,
    dbGifts.n === exp.gift.length, dbGifts);
  ok(`DB gift DOLLARS == the key ($${expDollars("gift")}, refunds NEGATIVE and netted)`,
    Math.abs(dbGifts.d - expDollars("gift")) < 0.02, dbGifts.d);
  const [negGifts] = await q(`SELECT COUNT(*)::int n, COALESCE(SUM(amount),0)::float d FROM gifts WHERE org_id=$1 AND amount < 0`, [ORG]);
  ok("the 9 refund rows imported as negative gifts (−$6,750)", negGifts.n === 9 && Math.abs(negGifts.d + 6750) < 0.01, negGifts);

  // Larry Ackerly — the man whose bad date became today
  const larry = await q(`SELECT g.date::text AS date, g.amount::float AS amount FROM gifts g JOIN donors d ON d.id=g.donor_id
                          WHERE d.org_id=$1 AND d.name='Larry Ackerly' ORDER BY g.date`, [ORG]);
  ok("Larry Ackerly has exactly his three gifts, on his three real dates (the USD row included)",
    JSON.stringify(larry.map(g => `${g.date.slice(0, 10)}|${g.amount}`)) === JSON.stringify(KEY.larryAckerly), larry);
  // strictly FUTURE is the error; a file date that has since arrived is a
  // real gift (the key's future rows re-derive at run time above).
  const [todayGifts] = await q(`SELECT COUNT(*)::int n FROM gifts WHERE org_id=$1 AND date::date > $2`, [ORG, TODAY]);
  ok("ZERO gifts dated after today — a bad date is an error, never a default", todayGifts.n === 0, todayGifts);

  // flags landed as first-class fields
  for (const [field, names] of [["deceased", KEY.exclusions.deceased], ["do_not_solicit", KEY.exclusions.doNotSolicit], ["do_not_contact", KEY.exclusions.doNotContact]]) {
    const rows = await q(`SELECT name FROM donors WHERE org_id=$1 AND ${field} IS TRUE`, [ORG]);
    const got = new Set(rows.map(r => r.name.toLowerCase()));
    ok(`${field} set on every key-named donor (${names.length})`,
      names.every(n => got.has(n.toLowerCase())), names.filter(n => !got.has(n.toLowerCase())));
  }
  const susDb = await q(`SELECT name, imported_sustainer_amount::float AS amt, imported_sustainer_last_gift FROM donors WHERE org_id=$1 AND imported_sustainer IS TRUE`, [ORG]);
  ok(`imported_sustainer set on the 34, each carrying amount + last gift`,
    susDb.length === KEY.sustainers.count && susDb.every(s => s.amt > 0 && s.imported_sustainer_last_gift), susDb.length);

  // ── §4 · the exclusions are ABSENT from every actionable surface ─────────
  console.log("\n— §4 · nobody tells anyone to call the dead —");
  const excluded = [...KEY.exclusions.deceased, ...KEY.exclusions.doNotSolicit, ...KEY.exclusions.doNotContact].map(n => n.toLowerCase());
  const pledgePayers = KEY.exclusions.pledgePayers.map(n => n.toLowerCase());

  const drift = (await api("GET", "/drift?all=1&includeMedium=1", tok)).body;
  const driftIds = drift.list.map(r => r.donorId);
  // Identity, not display names: the fixture deliberately contains TWO
  // different donors sharing the name "The Guillory Family" (one an
  // email-keyed quarterly giver who may legitimately drift, one a no-email
  // sustainer) — a name-matched assertion would be wrong in both directions.
  const flaggedOnDrift = driftIds.length ? await q(
    `SELECT name, deceased, do_not_contact, do_not_solicit, imported_sustainer FROM donors
      WHERE org_id=$1 AND id = ANY($2)
        AND (deceased IS TRUE OR do_not_contact IS TRUE OR do_not_solicit IS TRUE OR imported_sustainer IS TRUE)`,
    [ORG, driftIds]) : [];
  ok("no deceased / do-not-solicit / do-not-contact / unlinked-sustainer donor on the drift list",
    flaggedOnDrift.length === 0, flaggedOnDrift);
  const driftNames = drift.list.map(r => r.donorName.toLowerCase());
  ok("no pledge payer on the drift list (contractual cadence, not voluntary)",
    !driftNames.some(n => pledgePayers.includes(n)), driftNames.filter(n => pledgePayers.includes(n)));

  const attention = (await api("GET", "/dashboard/today?scope=all", tok)).body;
  const attnActionable = attention.filter(i => !["receipt", "receipt_mismatch"].includes(i.action));
  const attnIds = attnActionable.map(i => i.donorId).filter(Boolean);
  const flaggedOnAttn = attnIds.length ? await q(
    `SELECT name FROM donors WHERE org_id=$1 AND id = ANY($2)
        AND (deceased IS TRUE OR do_not_contact IS TRUE OR do_not_solicit IS TRUE)`, [ORG, attnIds]) : [];
  ok("no excluded donor in Needs Your Attention (outreach items)",
    flaggedOnAttn.length === 0, flaggedOnAttn.concat(attnActionable.filter(i => excluded.includes((i.donorName || "").toLowerCase())).map(i => `${i.donorName}: ${i.reason}`)));

  const atRiskUrl = await q(`SELECT id, name FROM donors WHERE org_id=$1 AND deleted_at IS NULL`, [ORG]);
  void atRiskUrl;
  // the at-risk auto-enroll candidates (feeds AI-drafted re-engagement email)
  const sim = (await api("GET", "/drift", tok)).body; void sim;
  const atRisk = await q(`
    SELECT name FROM donors
     WHERE org_id = $1 AND deleted_at IS NULL
       AND stage NOT IN ('prospect','lapsed')
       AND email IS NOT NULL AND email != ''
       AND last_gift_date IS NOT NULL AND last_gift_date::date < NOW() - INTERVAL '300 days'
       AND total_giving >= 5000
       AND deceased IS NOT TRUE AND do_not_contact IS NOT TRUE AND do_not_solicit IS NOT TRUE`, [ORG]);
  const atRiskAll = await q(`
    SELECT name FROM donors
     WHERE org_id = $1 AND deleted_at IS NULL AND total_giving >= 5000
       AND last_gift_date IS NOT NULL AND last_gift_date::date < NOW() - INTERVAL '300 days'
       AND (deceased IS TRUE OR do_not_contact IS TRUE OR do_not_solicit IS TRUE)`, [ORG]);
  ok(`the flags actually gate the at-risk shape (excluded pool: ${atRiskAll.length} would have qualified by money+silence alone)`,
    atRiskAll.length > 0 && !atRisk.some(r => excluded.includes(r.name.toLowerCase())), null);

  // ── §5 · the recurring surface sees imported sustainers (Part 5) ─────────
  console.log("\n— §5 · unlinked sustainers are visible, not zero —");
  const unlinked = (await api("GET", "/recurring/unlinked", tok)).body;
  ok(`the recurring surface counts the 34 imported sustainers (was zero)`,
    unlinked.counts.unlinked === KEY.sustainers.count, unlinked.counts);
  ok(`…and separates the ${KEY.sustainers.stoppedOver60d.length} whose giving stopped >60 days ago`,
    unlinked.counts.stopped === KEY.sustainers.stoppedOver60d.length, { got: unlinked.counts.stopped, expect: KEY.sustainers.stoppedOver60d.length });
  const stoppedRows = unlinked.list.filter(u => u.stopped);
  ok("a stopped sustainer's reason is their own story, never 'lapsed'",
    stoppedRows.length > 0 && stoppedRows.every(u => /a month/.test(u.reason) && !/lapsed/i.test(u.reason)),
    stoppedRows.slice(0, 2).map(u => u.reason));
  // routed OUT of lapsed: a stopped imported sustainer is not in the day view's lapsed bucket
  const attn2 = (await api("GET", "/dashboard/today?scope=all", tok)).body;
  const susIds = new Set(unlinked.list.map(u => u.donorId));
  ok("no imported sustainer appears in the Needs-Your-Attention lapsed bucket (their card stopped, they did not)",
    !attn2.some(i => i.action === "lapsed" && susIds.has(i.donorId)),
    attn2.filter(i => i.action === "lapsed" && susIds.has(i.donorId)).map(i => i.donorName));

  // ── §6 · the reconnect flow, through a LIVE test-mode webhook ────────────
  // A reconnect stitches the new subscription to the EXISTING donor (history
  // stays, lifetime does not reset); the negative — a reconnect matching
  // nothing — creates a new donor and never silently merges.
  console.log("\n— §6 · reconnect stitches to the existing donor —");
  const stripe = require("stripe")(process.env.STRIPE_SECRET_KEY || "sk_test_dummy");
  const WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET || "whsec_localtest";
  const ACCT = "acct_b77golden";
  await q(`UPDATE orgs SET stripe_account_id=$1, stripe_connected=true WHERE id=$2`, [ACCT, ORG]);
  const target = stoppedRows.find(u => u.email) || unlinked.list.find(u => u.email);
  const [before] = await q(`SELECT total_giving::float t, gift_count::int n FROM donors WHERE id=$1`, [target.donorId]);
  // send a reconnect link (records the intent; email fails to the dummy sink, harmless)
  const sendRes = await api("POST", "/recurring/unlinked/send-reconnect", tok, { donorIds: [target.donorId] });
  ok("send-reconnect records the send", sendRes.status === 200 && sendRes.body.sent >= 0, sendRes.body);
  // the token is deterministic — sign it the way the server does (HMAC over the id+org)
  const crypto = require("crypto");
  const SECRET = process.env.RECOVERY_SECRET || process.env.JWT_SECRET || "local-test-secret";
  const payload = Buffer.from(JSON.stringify({ donorId: target.donorId, orgId: ORG, k: "reconnect" })).toString("base64url");
  const sig = crypto.createHmac("sha256", SECRET).update(payload).digest("base64url");
  const reconnectToken = `${payload}.${sig}`;
  const fire = async evt => {
    const body = JSON.stringify(evt);
    const header = stripe.webhooks.generateTestHeaderString({ payload: body, secret: WEBHOOK_SECRET });
    const r = await fetch(BASE + "/stripe/webhook", { method: "POST", headers: { "Content-Type": "application/json", "stripe-signature": header }, body });
    return r.status;
  };
  // the checkout.session.completed a reconnect produces — reconnect_donor_id in metadata
  await fire({ id: "evt_b77_recon", type: "checkout.session.completed", account: ACCT,
    data: { object: { mode: "subscription", customer_email: target.email || "noemail@b77.test", customer: "cus_b77recon", subscription: "sub_b77recon", amount_total: 2500,
      metadata: { donor_name: target.donorName, frequency: "monthly", reconnect_donor_id: target.donorId } } } });
  await new Promise(r => setTimeout(r, 600));
  const [after] = await q(`SELECT id, total_giving::float t, gift_count::int n, imported_sustainer, stripe_subscription_id FROM donors WHERE id=$1`, [target.donorId]);
  ok("the reconnect stitched to the EXISTING donor — no second record, history intact",
    after && after.id === target.donorId && Math.abs(after.t - before.t) < 0.01 && after.n === before.n, { before, after });
  ok("…their subscription is now linked and the unlinked flag cleared",
    after.stripe_subscription_id === "sub_b77recon" && after.imported_sustainer === false, after);
  const [dupes] = await q(`SELECT COUNT(*)::int c FROM donors WHERE org_id=$1 AND name=$2`, [ORG, target.donorName]);
  ok("no duplicate donor row was created for the reconnected sustainer", dupes.c === 1, dupes);
  const recon = (await api("GET", "/recurring/unlinked", tok)).body;
  ok("the recovery number comes from the real event (1 reconnected, monthly-back > 0)",
    recon.stats.reconnected === 1 && recon.stats.monthlyBack > 0, recon.stats);
  // the negative: a reconnect token matching NOTHING creates a new donor, no silent merge
  await fire({ id: "evt_b77_recon_neg", type: "checkout.session.completed", account: ACCT,
    data: { object: { mode: "subscription", customer_email: "ghost-reconnect@b77.test", customer: "cus_b77ghost", subscription: "sub_b77ghost", amount_total: 1000,
      metadata: { donor_name: "Ghost Reconnect", frequency: "monthly", reconnect_donor_id: "d_does_not_exist" } } } });
  await new Promise(r => setTimeout(r, 500));
  const [ghost] = await q(`SELECT COUNT(*)::int c FROM donors WHERE org_id=$1 AND email='ghost-reconnect@b77.test'`, [ORG]);
  ok("a reconnect matching nothing creates a new donor (never a silent merge)", ghost.c === 1, ghost);

  await closeDb();
  summary();
})().catch(async e => { console.error("SUITE ERROR:", e); await closeDb().catch(() => {}); process.exit(1); });
